In [2]:
import cv2
import numpy

In [7]:
img = numpy.zeros((3,3), dtype=numpy.uint8)
print img
print img.shape

[[0 0 0]
 [0 0 0]
 [0 0 0]]
(3, 3)


In [23]:
img = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
print img
print img.shape

error: OpenCV(3.4.1) /home/spark/SW/opencv-3.4.1/modules/imgproc/src/color.cpp:11164: error: (-215) scn == 1 && (dcn == 3 || dcn == 4) in function cvtColor


In [3]:
image = cv2.imread('img/opencv-logo.png')
cv2.imshow("Image", image)
cv2.waitKey()
cv2.destroyAllWindows()
# cv2.imwrite('img/opencv-logo.jpg', image)