In [1]:
import numpy as np

In [5]:
a = np.linspace(-1, 1, 300)[:, np.newaxis]

In [6]:
print a.ndim

2


In [7]:
print a.shape

(300, 1)


In [8]:
b = np.linspace(-1, 1, 300)
print b.shape

(300,)


In [9]:
print b.ndim

1


In [ ]:
x_data = np.linspace(-1, 1, 300)[:, np.newaxis]
np.random.normal(0, 0.05, x_data.shape)

In [1]:
import numpy as np

test = np.array([[1, 2, 3], [2, 3, 4], [5, 4, 3], [8, 7, 2]])

In [2]:
test

array([[1, 2, 3],
       [2, 3, 4],
       [5, 4, 3],
       [8, 7, 2]])

In [3]:
np.argmax(test, 0)

array([3, 3, 1])

In [4]:
a = np.array([[1,1,1],[1,1,1]])
b = np.array([2,2,2])
np.add(a, b)

array([[3, 3, 3],
       [3, 3, 3]])

In [5]:
import tensorflow as tf

In [6]:
tf.truncated_normal?